### ISSUE TITLE
建议Rely参数加入对UIBarButtonItem的支持

### ISSUE THREAD

**Issue by jihongboo** [lyb5834/YBPopupMenu#1]
建议Rely参数加入对UIBarButtonItem的支持

**Comment by lyb5834** [comment]
建议使用 `[[UIBarButtonItem alloc] initWithCustomView:yourCustomButton]` 来实例化UIBarButtonItem，因为UIBarButtonItem没有公有方法获取它的view，用私有API虽然可以获取，但是可能会引起`APPStoreSafe`之类的问题

**Comment by jihongboo** [comment]
got it, 谢谢。建议你写进redme里面。
