### ISSUE TITLE
设置没有箭头不起作用

### ISSUE THREAD

**Issue by aizexin** [lyb5834/YBPopupMenu#10]
[YBPopupMenu showAtPoint:point titles:titleArray icons:nil menuWidth:AIscaleX(160) otherSettings:^(YBPopupMenu *popupMenu) {
        popupMenu.arrowDirection  = YBPopupMenuArrowDirectionNone;
        popupMenu.delegate   = self;
        popupMenu.tintColor  = ColorOfTheme_Main;
        popupMenu.cornerRadius    = 0;
//        popupMenu.offset     = AIscaleY(25);
    }];

**Comment by lyb5834** [comment]
嗯，设置了没有箭头我那个框架就不知道瞄点在哪了，更不能确认位置了，所以你要不显示箭头，可以这样设置`popupMenu.arrowWidth = 0;
            popupMenu.arrowHeight = 0;`  
这句`popupMenu.arrowDirection = YBPopupMenuArrowDirectionNone;`就删了吧，或者设置一个方向，但不要设置无方向，这个我下个版本会优化
