### ISSUE TITLE
确实设置cell选中时的效果，如下

### ISSUE THREAD

**Issue by asd8855** [lyb5834/YBPopupMenu#16]
cell.selectionStyle = UITableViewCellSelectionStyleNone;

**Comment by lyb5834** [comment]
你的意思是，开放一个是否有点击效果的属性？

**Comment by asd8855** [comment]
恩恩 你现在的是系统默认的！看着不太好看

**Comment by lyb5834** [comment]
现在增加了自定义cell的回调哦，想要什么样的效果自己设置吧！
