### ISSUE TITLE
看到你说代码全部重构，就看得出你花心思了。刚下载喵了一眼，说2个我看到的现象。

### ISSUE THREAD

**Issue by SPStore** [lyb5834/YBPopupMenu#17]
1.文本输入框呼唤出键盘后，你要让人家可以退出键盘啊，弹出来键盘就退不出去，还要人家重启程序。
2.如果在5s上运行，点击文本输入框，你的PopupMenu显示在文本输入框的上方，而5s屏幕比较小，以至于你的PopupMenu超出屏幕边界了，应该是没有做屏幕适配或者边界处理
3.iPhoneX出来了，要想让你的框架更被广泛使用，必须适配iPhoneX，iPhoneX是朵奇葩

**Comment by lyb5834** [comment]
感谢您提出的意见，您观察的很仔细，不过我还是要解释一下您提出的几个问题
1.demo中键盘呼出无法退出的问题，其实是可以退出的，点击键盘的return就可以了，因为是demo，没做点击空白处收回等策略
2.其实这个demo主要就是在5s等机器上才显示出问题来，PopupMenu超出屏幕边界是一定的，因为我限制死了方向，不会自动调整的，因为有的需求要弹出的方向固定的，我这算是一个测试吧，无论屏幕多小，箭头一直在下方~
3.这个我最近还没有时间测，不过我的是基于window弹出的，理论上来说不存在适配问题~
