### ISSUE TITLE
cell能自定义就很棒了 现在只能修改源代码了

### ISSUE THREAD

**Issue by ZhongYanga** [lyb5834/YBPopupMenu#18]

**Comment by lyb5834** [comment]
已经可以自定义cell了哦，欢迎下载使用

**Comment by ZhongYanga** [comment]
大神提两点建议啊 可能只是我个人的需求
1.YBPopupMenuDelegate代理方法最好加个参数把popmenu传出来
2.增加一个属性存储选中的index，因为当用户选中某项时，可能下次弹出要显示上一次选中的index
```
- (void)ybPopupMenuDidDismiss:(YBPopupMenu *)popMenu;
popupMenu.selectedIndex = weakSelf.lastSelectedIndex;
```

**Comment by lyb5834** [comment]
好，下个版本我改掉

**Comment by chengongwen** [comment]
![image](https://user-images.githubusercontent.com/9940006/69937365-8f3f2c80-1515-11ea-933f-cefe4cdfee64.png)
![image](https://user-images.githubusercontent.com/9940006/69937464-d0cfd780-1515-11ea-9413-cd2a63533c26.png)

大神提点建议啊：这个严重越界了，怎么破

**Comment by lyb5834** [comment]
> ![image](https://user-images.githubusercontent.com/9940006/69937365-8f3f2c80-1515-11ea-933f-cefe4cdfee64.png)
> ![image](https://user-images.githubusercontent.com/9940006/69937464-d0cfd780-1515-11ea-9413-cd2a63533c26.png)
> 
> 大神提点建议啊：这个严重越界了，怎么破

额，你这个无论向上还是向下都放不下了。。。。
我的那个逻辑是（优先箭头向上的话）如果放不下就反转popmenu，现在明显就是已经反转了，但还是放不下，反转后我是不会再判断是否放不放的下的，你最好和产品商量下布局，改小点
