### ISSUE TITLE
关于点击按钮弹出menu的问题

### ISSUE THREAD

**Issue by Crayonnerry** [lyb5834/YBPopupMenu#21]
这边基于点击按钮自动判断向上弹还是向下弹，这边的一个标准是什么？按钮处于什么位置是是向下弹的？为什么我把按钮设置在了中间偏下 他也会往下弹？

**Comment by lyb5834** [comment]
根据屏幕的边界判断的，当菜单会超出屏幕时会反转弹出方向，可以通过设置 `priorityDirection` 这个枚举设置弹出方向的优先级




发自网易邮箱大师


在2018年06月19日 13:50，Crayonnerry<notifications@github.com> 写道：

这边基于点击按钮自动判断向上弹还是向下弹，这边的一个标准是什么？按钮处于什么位置是是向下弹的？为什么我把按钮设置在了中间偏下 他也会往下弹？
