### ISSUE TITLE
急急急，如何更新或去掉cell中间的分割线

### ISSUE THREAD

**Issue by Isaaclzg** [lyb5834/YBPopupMenu#22]

**Comment by Isaaclzg** [comment]
已经解决 自定cell的时候隐藏分割线才生效 ，不知道是不是我的问题
`popupMenu.tableView.separatorStyle = UITableViewCellSeparatorStyleNone;`

**Comment by lyb5834** [comment]
嗯，我的分割线是自己画的，但是是私有方法，遇到奇葩需求就自定义cell吧




发自网易邮箱大师


在2018年07月3日 11:19，isaac_gang<notifications@github.com> 写道：

已经解决 自定cell的时候隐藏分割线才生效 ，不知道是不是我的问题
popupMenu.tableView.separatorStyle = UITableViewCellSeparatorStyleNone;
