### ISSUE TITLE
提个小细节，不知道有没有注意到

### ISSUE THREAD

**Issue by chenliqian** [lyb5834/YBPopupMenu#23]
提个小细节，不知道有没有注意到
YBPopupMenu圆角的时候，选中边角会把圆角变方了
当然只是小细节

**Comment by lyb5834** [comment]
说吧，什么细节

**Comment by chenliqian** [comment]
就是选中第一行或者是最后一行，带圆角的cell会变回没有圆角

**Comment by lyb5834** [comment]
嗯，我cell没有切圆角，不然影响性能了，如果觉得不合适可以自定义cell

**Comment by chenliqian** [comment]
没毛病，小问题
