### ISSUE TITLE
文字不能居中

### ISSUE THREAD

**Issue by xhjss** [lyb5834/YBPopupMenu#24]
加上文字可以居中最好

**Comment by lyb5834** [comment]
可以的，不过不能直接设置，要在attribute里设置




| |
李渊博
邮箱：lyb5834@126.com
|

签名由 网易邮箱大师 定制

在2018年08月22日 17:08，xhjss 写道：

加上文字可以居中最好

**Comment by xhjss** [comment]
![image](https://user-images.githubusercontent.com/7153138/44455046-acf1c680-a62f-11e8-8360-6f9cbeb3d45b.png)
还是没居中哈

 NSMutableArray *titleList = [NSMutableArray new];
    NSArray *titles = @[RELocalized(@"财务记录"),RELocalized(@"搜索资产"),RELocalized(@"钱包设置")];
    for (NSString *title in titles) {
        NSMutableAttributedString *text = [[NSMutableAttributedString alloc]initWithString:title];
        text.font = RESystemFont(16);
        text.color = REColor_77_90_109;
        text.alignment = NSTextAlignmentCenter;
        [titleList addObject:title];
    }
    YBPopupMenu *menu = [YBPopupMenu showRelyOnView:sender titles:titleList icons:nil menuWidth:104 otherSettings:^(YBPopupMenu *popupMenu) {
        popupMenu.cornerRadius = 10;
        popupMenu.tableView.separatorStyle = UITableViewCellSeparatorStyleSingleLine;
        popupMenu.itemHeight = 50;
    }];

**Comment by xhjss** [comment]
这个应该是cell 里面问题，需要自定义cell吧

**Comment by lyb5834** [comment]
搞错了，我以为你说的是我另一个框架，遇到奇葩需求最好自定义吧~

**Comment by zeku2022** [comment]
自定义cell吧...不过可能圆角就不能用了

**Comment by intelegraphics** [comment]
挺多是不许需要图片，文字居中的需求

**Comment by intelegraphics** [comment]
if (!cell) {
        cell = [[YBPopupMenuCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:identifier];
        cell.textLabel.numberOfLines = 0;
    }
 cell.textLabel.textAlignment = NSTextAlignmentCenter;

应该提供一个属性标识是否让文字居中，或者设计成如果没有图片就自动让文字居中UITableViewCellStyleDefault 和cell.textLabel.textAlignment = NSTextAlignmentCenter;

**Comment by lyb5834** [comment]
嗯，你先自定义cell解决了需求吧，等我得空了更新一版

**Comment by OdasokenIkii** [comment]
static NSString * identifier = @"ybPopupMenu";
    static NSString * onlyTitleIdentifier = @"ybOnlyTitlePopupMenu";
    //先判断是否存在图片
    UIImage *currentImage = nil;
    if (_images.count >= indexPath.row + 1)
    {
        if ([_images[indexPath.row] isKindOfClass:[NSString class]])
        {
            currentImage = [UIImage imageNamed:_images[indexPath.row]];
        }else if ([_images[indexPath.row] isKindOfClass:[UIImage class]])
        {
            currentImage = _images[indexPath.row];
        }
    }
    
    YBPopupMenuCell *cell = nil;
    if (currentImage == nil)
    {
        cell = [tableView dequeueReusableCellWithIdentifier:onlyTitleIdentifier];
        if (!cell)
        {
            cell = [[YBPopupMenuCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:identifier];
            cell.textLabel.numberOfLines = 0;
        }
        cell.textLabel.textAlignment = NSTextAlignmentCenter;

    }else
    {
        cell = [tableView dequeueReusableCellWithIdentifier:identifier];
        if (!cell)
        {
            cell = [[YBPopupMenuCell alloc] initWithStyle:UITableViewCellStyleValue1 reuseIdentifier:identifier];
            cell.textLabel.numberOfLines = 0;
        }
        cell.imageView.image = currentImage;
    }
我是复制代码的，所以我在源代码里改成了自动居中。

**Comment by OdasokenIkii** [comment]
` 
static NSString * identifier = @"ybPopupMenu";
 static NSString * onlyTitleIdentifier = @"ybOnlyTitlePopupMenu";
    //先判断是否存在图片
    UIImage *currentImage = nil;
    if (_images.count >= indexPath.row + 1)
    {
        if ([_images[indexPath.row] isKindOfClass:[NSString class]])
        {
            currentImage = [UIImage imageNamed:_images[indexPath.row]];
        }else if ([_images[indexPath.row] isKindOfClass:[UIImage class]])
        {
            currentImage = _images[indexPath.row];
        }
    }
    
    YBPopupMenuCell *cell = nil;
    if (currentImage == nil)
    {
        cell = [tableView dequeueReusableCellWithIdentifier:onlyTitleIdentifier];
        if (!cell)
        {
            cell = [[YBPopupMenuCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:onlyTitleIdentifier];
            cell.textLabel.numberOfLines = 0;
        }
        cell.textLabel.textAlignment = NSTextAlignmentCenter;

    }else
    {
        cell = [tableView dequeueReusableCellWithIdentifier:identifier];
        if (!cell)
        {
            cell = [[YBPopupMenuCell alloc] initWithStyle:UITableViewCellStyleValue1 reuseIdentifier:identifier];
            cell.textLabel.numberOfLines = 0;
        }
        cell.imageView.image = currentImage;
    }
'
我是复制代码的，所以我在源代码里改成了自动居中。
