### ISSUE TITLE
你的代码能不能有时间优化一下？

### ISSUE THREAD

**Issue by k214k** [lyb5834/YBPopupMenu#26]
建议你把这个库的代码优化一下。

**Comment by lyb5834** [comment]
哪方面优化？

**Comment by k214k** [comment]
例如：不能频繁调用：- (void)updateUI
还有我在- (void)updateUI这个方法中调用    //[self setRelyRect];      //[self setAnchorPoint];
    //[self setOffset];    能不能注释掉，我看了代码，没有必要调用，不知道我说的对不对？我把这几个注释了，不影响布局的。我自己参照你的代码，写了一个简化版。

**Comment by lyb5834** [comment]
你用新的方法注释没问题的，我为了兼容老实例化接口




| |
李渊博
邮箱：lyb5834@126.com
|

签名由 网易邮箱大师 定制

在2018年08月29日 17:25，k214k 写道：

例如：不能频繁调用：- (void)updateUI
还有我在- (void)updateUI这个方法中调用 //[self setRelyRect]; //[self setAnchorPoint];
//[self setOffset]; 能不能注释掉，我看了代码，没有必要调用，不知道我说的对不对？我把这几个注释了，不影响布局的。

**Comment by StarRiverr** [comment]
- (void)updateUI这个调用太频繁了，交互复杂的情况下影响性能

**Comment by lyb5834** [comment]
现在我项目比较忙，我已经有优化的思路了，不再兼容老的接口，防止频繁调`updateUI `这个问题，还有转屏适配等等，我会抽时间优化下的

**Comment by StarRiverr** [comment]
> 现在我项目比较忙，我已经有优化的思路了，不再兼容老的接口，防止频繁调`updateUI `这个问题，还有转屏适配等等，我会抽时间优化下的

嗯嗯 其实不看源码用起来还是挺方便的

**Comment by lyb5834** [comment]
已优化，`updateUI `方法不会频繁调用了
