### ISSUE TITLE
貌似自定义Cell后,没法设置全圆角了,死循环了 麻烦看看...

### ISSUE THREAD

**Issue by zeku2022** [lyb5834/YBPopupMenu#27]
如题...得优化一下.

**Comment by lyb5834** [comment]
你试试把自定义cell和cell的contentView的背景色设置透明

**Comment by zeku2022** [comment]
> 你试试把自定义cell和cell的contentView的背景色设置透明

谢谢回复,我刚自己多试了几个方法,发现直接设置tableview的cornerRadius为5就好了...
