### ISSUE TITLE
cell两边的边距如何调整？？现在的有点大

### ISSUE THREAD

**Issue by gongqiuwei** [lyb5834/YBPopupMenu#28]

**Comment by lyb5834** [comment]
不太明白你的意思，能说详细点吗


在2018年10月11日 17:33，gongqiuwei<notifications@github.com> 写道：

**Comment by gongqiuwei** [comment]
对不起，是我没描述清楚，如图两边的间距
![Uploading 6E84F07B-EAD5-4FD8-8149-5CFC8AB9E6E0.png…]()

自定义cell添加自己的label可以解决，但是如果我不想自定义的话就做不到了。。希望能增加一个调整的接口，方便修改UI效果

**Comment by gongqiuwei** [comment]
图片没穿好，sorry ![6e84f07b-ead5-4fd8-8149-5cfc8ab9e6e0](https://user-images.githubusercontent.com/3827831/46843519-cb8d6600-ce05-11e8-92fc-7a968ef43587.png)

**Comment by lyb5834** [comment]
这个是系统cell的边距，大概是16的样子，如果要调整，建议自定义cell，我提供了自定义cell的接口


在2018年10月12日 10:01，gongqiuwei<notifications@github.com> 写道：

图片没穿好，sorry

**Comment by gongqiuwei** [comment]
UI设计的间隙每个人都是不一致的，这个是使用的时候频繁修改的点，希望能便捷点，每次都要自定义不是特别方便（想偷懒😄，。。。）
