### ISSUE TITLE
在有导航栏的情况下

### ISSUE THREAD

**Issue by LZAscott** [lyb5834/YBPopupMenu#3]
在有导航栏的情况下，如果开启了self.navigationController.navigationBar.translucent = NO;  则显示会上移。

**Comment by lyb5834** [comment]
我测试了正常啊。。。

**Comment by lyb5834** [comment]
你是用的`showAtPoint`那个方法吧？那是坐标计算的问题，只需设置offset = 64即可，另外，`showRelyOnView`因为获取了view对象，不会出现这个问题

**Comment by LZAscott** [comment]
恩，我已经通过增加一个属性解决了。
