### ISSUE TITLE
在-show方法中获取最后一个可见的cell有问题

### ISSUE THREAD

**Issue by DeanFs** [lyb5834/YBPopupMenu#30]
在-show方法中通过getLastVisibleCell获取最后一个可见的cell时有问题，如下图
![151558955465_ pic](https://user-images.githubusercontent.com/48240371/58416125-30ef4800-80b3-11e9-9dc5-13a8a1667eeb.jpg)

改进方案：
<img width="802" alt="image" src="https://user-images.githubusercontent.com/48240371/58416225-6f850280-80b3-11e9-9f9f-315c69cd61d7.png">

另外能否开发设置阴影透明度和颜色属性，默认的阴影有些生硬。
谢谢作者提供好用的控件，忘能改进以上两项，
再次感谢~

**Comment by lyb5834** [comment]
好的，感谢指出




在2019年05月27日 19:15，Dean_F 写道：

在-show方法中通过getLastVisibleCell获取最后一个可见的cell时有问题，如下图


改进方案：


另外能否开发设置阴影透明度和颜色属性，默认的阴影有些生硬。
谢谢作者提供好用的控件，忘能改进以上两项，
再次感谢~

**Comment by lyb5834** [comment]
阴影之类的我会考虑重写那块的，主要是代码创建的比较早，那时候也没考虑那么多
