### ISSUE TITLE
cell高度自适应的接口

### ISSUE THREAD

**Issue by xiaoojun** [lyb5834/YBPopupMenu#31]
作者能提供 一个cell高度自适应的接口

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by lyb5834** [comment]
这个不太好弄，我整个的计算都是基于cell的高度的，牵一发动全身，改动比较多，这个再说吧
