### ISSUE TITLE
死循环了怎么办

### ISSUE THREAD

**Issue by mengxinyizhui** [lyb5834/YBPopupMenu#32]
![屏幕快照 2019-12-17 上午11 34 05](https://user-images.githubusercontent.com/14011250/70962751-27feac00-20c1-11ea-8c5e-97e3a354ef98.png)
死循环了？？？？

**Comment by lyb5834** [comment]
什么情况下会这样？？

**Comment by lyb5834** [comment]
问题不活跃关闭
