### ISSUE TITLE
How to dismiss menu programmatically?

### ISSUE THREAD

**Issue by skuske** [lyb5834/YBPopupMenu#33]
There's no way to programmatically dismiss a menu? How can I dismiss a menu by code? Thanks. :o)

**Comment by lyb5834** [comment]
```
    YBPopupMenu * popupMenu = [YBPopupMenu showAtPoint:point titles:TITLES icons:nil 
      menuWidth:110 otherSettings:^(YBPopupMenu *popupMenu) {
        popupMenu.dismissOnSelected = YES;
        popupMenu.xxx
        ...
    }];
    [popupMenu dismiss];
```

you can try this function

**Comment by skuske** [comment]
@lyb5834 

Thanks for your rapid reply.

Unfortunately this does not work, as I want to call `dismiss` from inside `viewWillDisappear`, otherwise a menu that is currently open will remain visible even after the containing ViewController has been dismissed.

What I want o achieve is: **close all menus** that might still be open, **then** dismiss the ViewController...

**Comment by lyb5834** [comment]
well, YBPopupMenu's superView is the main window, so you can  refer to the following code
```
[[UIApplication sharedApplication].delegate.window.subviews enumerateObjectsUsingBlock:^(__kindof UIView * _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
        
       if ([obj isMemberOfClass:[YBPopupMenu class]]) {
           YBPopupMenu * popupMenu = (YBPopupMenu *)obj;
           [popupMenu dismiss];
       }
        
}];
```

**Comment by skuske** [comment]
@lyb5834 

Cool, many thanks.
