### ISSUE TITLE
1、duration设置无效；2、选择YBPopupMenuAnimationStyleNone不能触发点击回调

### ISSUE THREAD

**Issue by MichaelZhe** [lyb5834/YBPopupMenu#34]

**Comment by MichaelZhe** [comment]
1、似乎与动画manager的调用顺序有关。
2、dismiss方法中，会在动画结束后将delegate置空，而没有动画时会立即置空（即在触发回调之前就会置空）

**Comment by lyb5834** [comment]
1.duration 是我这边的问题，我下个版本把这个问题修复，暂时可以先设置duration 再设置下style，duration属性就生效了
2.我这边无法复现
