### ISSUE TITLE
在 iOS13 以上的系统里，弹不出来

### ISSUE THREAD

**Issue by boxkim** [lyb5834/YBPopupMenu#36]
应该是这一句在 iOS13 里拿不到 window `#define YBMainWindow  [UIApplication sharedApplication].delegate.window`

改成  `#define YBMainWindow  [[UIApplication sharedApplication] keyWindow]`  就没问题了

**Comment by lyb5834** [comment]
OK 多谢指出，你是新建的项目吧，新建的 window 不在 appDelegate 了

**Comment by lyb5834** [comment]
已修复
