### ISSUE TITLE
menuBackView 遮罩层背景颜色无法自定义

### ISSUE THREAD

**Issue by boai** [lyb5834/YBPopupMenu#40]
menuBackView 遮罩层背景颜色无法自定义

**Comment by CoderWeiLee** [comment]
> menuBackView 遮罩层背景颜色无法自定义

你实现了阴影效果了吗

**Comment by lyb5834** [comment]
嗯，我的这个框架是5年前就写了，虽然不断维护，但是不可避免的还有一些无法自定义的属性，等我整理下，再重构一版
