### ISSUE TITLE
现在似乎只能通过类方法来创建使用

### ISSUE THREAD

**Issue by CoderWeiLee** [lyb5834/YBPopupMenu#42]
遇到一个问题，需要用户在TextField中，随着输入公司名称的同时，不停匹配相应的名称数据。这样子似乎会不停创建PopMenu堆积在界面上，而且titles和images数组属性也是只读的，无法设置

**Comment by lyb5834** [comment]
嗯，我的这个框架是弹窗性质的，你说的这种需求可能不太适合用这个框架
