### ISSUE TITLE
无法修改线条颜色

### ISSUE THREAD

**Issue by huhangatzz** [lyb5834/YBPopupMenu#43]
我这里使用了iOS14.4.1系统，测试想修改线条颜色，发现一个问题，当我在- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier这个方法里面打印_separatorColor属性的时候输出是UIExtendedSRGBColorSpace 1 0 0 1，但是当我在- (void)drawRect:(CGRect)rect里面打印的时候输出的是<UIDynamicSystemColor: 0x283a45440; name = separatorColor>，不管怎么修改_separatorColor颜色，都是无法改变的。所以如果解决此问题呢

**Comment by lyb5834** [comment]
这个是历史遗留问题，下个版本我会优化，如果你一定要自定义线条颜色，你暂时可以自定义cell解决

**Comment by huhangatzz** [comment]
我已经自定义cell了，感谢回复---- 回复的原邮件 ----发件人yuanbo ***@***.***>发送日期2021年11月10日 11:13 ***@***.***> ***@***.******@***.***>主题Re: [lyb5834/YBPopupMenu] 无法修改线条颜色 (#43)

这个是历史遗留问题，下个版本我会优化，如果你一定要自定义线条颜色，你暂时可以自定义cell解决



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.



[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/lyb5834/YBPopupMenu/issues/43#issuecomment-964747168",

"url": "https://github.com/lyb5834/YBPopupMenu/issues/43#issuecomment-964747168",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
