### ISSUE TITLE
能给列表设置小红点吗，比如有新消息的时候

### ISSUE THREAD

**Issue by SuAdrenine** [lyb5834/YBPopupMenu#8]
比如给修改右上角加一个小红点，怎么拿到修改这个View

**Comment by lyb5834** [comment]
这种需求太个别了，我没考虑到，你可以直接修改源码中的cell的方法手动添加

**Comment by SuAdrenine** [comment]
其实这种需求很常见的，你这种弹出小列表的，很多时候都会有那种消息提示的小红点，改源码手动获取cell其实并不方便

**Comment by lyb5834** [comment]
现在可以自定义cell了哦，想要什么效果可以自己设置

**Comment by SuAdrenine** [comment]
好的，谢谢！
